# Settings
title: "David King's ePortfolio"
author: "David King"
description: "A showcase of my bachelor's degree work, including all work for the CS 499 Capstone Course."

# Theme
theme: jekll-theme-cayman

# Customization
show_excerpts: true  # Enables post previews instead of full content
permalink: /:title/  # Simplifies URL structure

# Navigation?
